### ISSUE TITLE
TypeError: Cannot call method 'ast_walker' of undefined

### ISSUE THREAD

**Issue by helder-robalo** [voloko/uki#45]
I'm trying to run locally and I'm getting this error, the same using facebook/powereditor who uses uki.
Somebody told me I should change uglify's version, but I do rollback until uglify-js@2.3.6 and still getting error.

``` shell

<PATH>\ukijs-test\node_modules\ukijs>node express.js

<PATH>\ukijs-test\node_modules\ukijs\tools\static_require.js:36
var walker = pro.ast_walker(),
                 ^
TypeError: Cannot call method 'ast_walker' of undefined
    at Object.<anonymous> (<PATH>\ukijs-test\node_modules\ukijs\t
ools\static_require.js:36:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<PATH>\node_modules\ukijs\e
xpress.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by minakolta** [comment]
any solution?!, I've just installed it on CentOS with the same exact error

**Comment by helder-robalo** [comment]
@minakolta Not yet, I had to change my UI stack at that time. Now I don't know if there's a solution

**Comment by mgdombrowski** [comment]
You can fix this if you roll back to uglify-js 1.3.4. You'll also need express circa v2.5:

```
npm uninstall uglify-js
npm install uglify-js@1.3.4

npm uninstall express
npm install express@2.5.0
```

**Comment by helder-robalo** [comment]
@mgdombrowski Thanks Sir, that's resolved the problem
